object IntError 
  def foo(): Int = { 42 }
end IntError